name: Weekly Report CI/CD

on:
  push:
    branches: [main]
    tags: ["v*"]
  schedule:
    - cron: '0 10 * * 4'  # 매주 목요일 오전 10시
  workflow_dispatch:

env:
  APP_NAME: weekly_report
  GITLAB_DOCKER_IMAGE: ghcr.io/your-org/weekly_report

jobs:
  release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Create Git Tag and Push
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          TAGS=$(git describe --abbrev=0 --tags || echo "v0.0.0")
          VERSION=$(echo $TAGS | sed s/v//).${{ github.run_number }}
          git tag v${VERSION}
          git push https://x-access-token:${PERSONAL_ACCESS_TOKEN}@github.com/${{ github.repository }}.git v${VERSION}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: New release - v${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-build-and-push:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -f Dockerfile -t $GITLAB_DOCKER_IMAGE:${GITHUB_REF_NAME} .
          docker tag $GITLAB_DOCKER_IMAGE:${GITHUB_REF_NAME} $GITLAB_DOCKER_IMAGE:latest
          docker push $GITLAB_DOCKER_IMAGE:${GITHUB_REF_NAME}
          docker push $GITLAB_DOCKER_IMAGE:latest

  run-weekly-report:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Run Weekly Report Container
        run: |
          docker pull $GITLAB_DOCKER_IMAGE:latest
          docker run --rm \
            -e CONFLUENCE_API_TOKEN="${{ secrets.CONFLUENCE_API_TOKEN }}" \
            -e ROOT_PAGE_ID="${{ secrets.ROOT_PAGE_ID }}" \
            -e CONFLUENCE_BASE_URL="${{ secrets.CONFLUENCE_BASE_URL }}" \
            -e WEEKLY_REPORT_WEBHOOK_URL="${{ secrets.WEEKLY_REPORT_WEBHOOK_URL }}" \
            --name $APP_NAME \
            $GITLAB_DOCKER_IMAGE:latest
